name: Code Formatting Check

on:
  pull_request:
    branches: main

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: cd to `src`
        run: |
          echo "Current Working Directory:"
          pwd

          echo "Switching to ./src:"
          cd src

          echo "Listing all files in pwd:"
          ls -al
        

      - name: Check code formatting
        run: npx prettier --check .