name: Deploy to Firebase Hosting on merge of PR to main (only if files in "public" directory changed)
on:
  push:
    branches:
      - main
jobs:
  hosting_build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Checks out repository code

      - name: Verify Changes Exclusively in 'public' Directory
        id: check_changes
        run: |
          # Fetch the previous commit on the main branch
          git fetch origin main
          
          # Get the list of files that were changed in the last commit
          CHANGED_FILES=$(git diff --name-only origin/main ${{ github.sha }})
          echo "Changed files: $CHANGED_FILES"
          
          # Check if any files outside the 'public' directory were changed
          OUTSIDE_PUBLIC=$(echo "$CHANGED_FILES" | grep -v "^public/" || true)
          echo "Files outside the 'public' directory: $OUTSIDE_PUBLIC"
          
          # Check if no changes were made or changes are outside 'public'
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changes detected. Skipping deployment."
            exit 1
          elif [ -n "$OUTSIDE_PUBLIC" ]; then
            echo "Deployment aborted: Changes detected outside 'public' folder."
            exit 1
          else
            echo "Only 'public' folder was changed. Proceeding with deployment."
          fi

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SALE_CHECK_B611B }}
          channelId: live
          projectId: sale-check-b611b
          continue-on-error: false
