name: Deploy Firebase Functions on Merge of PR to `main` 

on:
  push:
    branches:
      - main  
  pull_request:
    branches-ignore:
      - main
      
jobs:
  npm-audit:
    uses: ./.github/workflows/npm-audit.yml
    with:
      working-directory: "functions"

  firebase_functions_deploy:
    needs: npm-audit  # Ensure npm-audit job is completed before this one
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  

      - name: Set up Node.js
        uses: actions/setup-node@v3  
        with:
          node-version: '18'
          continue-on-error: false

      - name: Dependencies for 'functions' Install
        run: |
          cd functions
          npm install 

      - name: Install Firebase CLI
        run: npm install -g firebase-tools  

      - name: Authenticate with Firebase
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SALE_CHECK_B611B }}" > $HOME/firebase-key.json  # Authenticate with Firebase using service account
        env:
          FIREBASE_SERVICE_ACCOUNT_SALE_CHECK_B611B: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SALE_CHECK_B611B }}

      - name: Deploy Firebase Functions
        run: firebase deploy --only functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $HOME/firebase-key.json  # Points to Firebase service account key
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}  # Stored in repo secrets